[package]
name = "cw-pause-once"
version = "0.0.1"
edition = "2021"
authors = ["ekez <ekez@withoutdoing.com>"]
description = "a package to allow an address to pause a single time for a prespecified duration"

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-utils = { workspace = true }
cw-storage-plus = { workspace = true }
thiserror = { workspace = true }
